### ISSUE TITLE
.png upload error

### ISSUE THREAD

**Issue by ha4219** [ha4219/jewelry#13]
/uploader

png file upload시 다음 에러가 뜸

```text
File "/home/dnatuna/jewelry/Face-alignment/face_alignment/detection/sfd/sfd_detector.py", line 33, in detect_from_image
    bboxlist = detect(self.face_detector, image, device=self.device)[0]
  File "/home/dnatuna/jewelry/Face-alignment/face_alignment/detection/sfd/detect.py", line 20, in detect
    img = img - np.array([104, 117, 123])
ValueError: operands could not be broadcast together with shapes (512,512,4) (3,)
```

아래 수정
```python
def image_save_with_resize(image, image_path):
    img = Image.open(image)
    img = img.resize((512, 512), Image.BILINEAR)
    img.save(image_path)
```

**Comment by ha4219** [comment]
https://stackoverflow.com/questions/9166400/convert-rgba-png-to-rgb-with-pil

```python
def image_save_with_resize(image, image_path):
    img = Image.open(image)
    img = img.resize((512, 512), Image.BILINEAR)
    # img.save(image_path)
    img.convert('RGB').save(image_path)
```

**Comment by ha4219** [comment]
#14

**Comment by ha4219** [comment]
```text
Traceback (most recent call last):
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dnatuna/jewelry/server/app.py", line 177, in uploader_file
    execute_face_alignment(front_image_path, fa_dst_path)
  File "/home/dnatuna/jewelry/server/app.py", line 60, in execute_face_alignment
    np.array(preds).tofile(dst_path)
OSError: cannot write object arrays to a file in binary mode
```

테스트 해보니까 이전 에러 다시 뜨네
