### ISSUE TITLE
cuda error out of memory

### ISSUE THREAD

**Issue by ha4219** [ha4219/jewelry#16]
```
Namespaces are one honking great idea -- let's do more of those!
Traceback (most recent call last):
  File "./app.py", line 38, in <module>
    FA = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False)
  File "/home/dnatuna/jewelry/Face-alignment/face_alignment/api.py", line 70, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "/home/dnatuna/jewelry/Face-alignment/face_alignment/detection/sfd/sfd_detector.py", line 28, in __init__
    self.face_detector.to(device)
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/nn/modules/module.py", line 852, in to
    return self._apply(convert)
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/nn/modules/module.py", line 850, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
```

**Comment by ha4219** [comment]
```
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
Traceback (most recent call last):
  File "./app.py", line 38, in <module>
    FA = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, device='cpu', flip_input=False)
  File "/home/dnatuna/jewelry/Face-alignment/face_alignment/api.py", line 80, in __init__
    self.face_alignment_net.load_state_dict(torch.load(os.path.join(os.path.dirname(__file__), 'pretrained_models', '3DFAN4-7835d9f11d.pth.tar')))
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/serialization.py", line 743, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/serialization.py", line 155, in _cuda_deserialize
    return storage_type(obj.size())
  File "/home/dnatuna/anaconda3/envs/face/lib/python3.7/site-packages/torch/cuda/__init__.py", line 528, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
